- name: Install ghidra
  import_tasks: ghidra.yml

- name: Install poetry
  ansible.builtin.pip:
    name: poetry

- name: Clone attack_surface_approximation from GitHub
  ansible.builtin.git:
    repo: https://github.com/CyberReasoningSystem/attack_surface_approximation.git
    dest: /home/{{ username }}/attack_surface_approximation
    recursive: True

- name: Install attack_surface_approximation deps
  ansible.builtin.shell: PATH=/home/{{ username }}/.local/bin:$PATH poetry install --no-dev
  args:
    chdir: /home/{{ username }}/attack_surface_approximation/

- name: Build attack_surface_approximation docker container
  ansible.builtin.shell: docker build --tag qbdi_args_fuzzing others/qbdi_docker
  args:
    chdir: /home/{{ username }}/attack_surface_approximation/
