- name: Install poetry
  ansible.builtin.pip:
    name: poetry

- name: Clone dataset from GitHub
  ansible.builtin.git:
    repo: https://github.com/CyberReasoningSystem/dataset.git
    dest: /home/{{ username }}/dataset
    recursive: True

- name: Install dataset deps
  ansible.builtin.shell: PATH=/home/{{ username }}/.local/bin:$PATH poetry install --no-dev
  args:
    chdir: /home/{{ username }}/dataset/
    executable: /bin/bash

- name: Build dataset docker container
  ansible.builtin.shell: docker build --tag ubuntu_32bit_compilator others/ubuntu_32bit_compilator
  args:
    chdir: /home/{{ username }}/dataset/

