- name: Install JDK-11
  apt:
    name: ["openjdk-11-jdk"]
    state: latest
    update_cache: true
  become: yes

- name: Create /opt dir
  ansible.builtin.file:
    path: /opt
    state: directory
    mode: "0755"
  become: yes

- name: Download and extract Ghidra 10.1.5
  ansible.builtin.unarchive:
    src: https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.1.5_build/ghidra_10.1.5_PUBLIC_20220726.zip
    dest: /opt
    remote_src: yes
  become: yes

- name: Create /opt/ghidra symlink
  ansible.builtin.file:
    src: /opt/ghidra_10.1.5_PUBLIC
    dest: /opt/ghidra
    state: link
    mode: "0755"
  become: yes
