- name: Install poetry
  ansible.builtin.pip:
    name: poetry

- name: Clone vulnerability_detection from GitHub
  ansible.builtin.git:
    repo: https://github.com/CyberReasoningSystem/vulnerability_detection.git
    dest: /home/{{ username }}/vulnerability_detection
    recursive: True

- name: Install vulnerability_detection deps
  ansible.builtin.shell: PATH=/home/{{ username }}/.local/bin:$PATH poetry install --no-dev
  args:
    chdir: /home/{{ username }}/vulnerability_detection/

- name: Build vulnerability_detection docker container
  ansible.builtin.shell:
    cmd: docker build --build-arg USER_ID=$(id -u {{ username }}) --build-arg GROUP_ID=$(id -g {{ username }}) --tag aflplusplus others/aflplusplus_docker
    chdir: /home/{{ username }}/vulnerability_detection/
